# To install the git pre-commit hook run:
#   pre-commit install
# To update the pre-commit hooks run:
#   pre-commit install-hooks
exclude: '^(\.tox|ci/templates|\.bumpversion\.cfg)(/|$)'
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: master
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: debug-statements
  - repo: https://github.com/timothycrosley/isort
    rev: main
    hooks:
      - id: isort
  - repo: https://github.com/ambv/black
    rev: 21.7b0
    hooks:
      - id: black
  - repo: https://gitlab.com/pycqa/flake8
    rev: master
    hooks:
      - id: flake8
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910
    hooks:
      - id: mypy
        args:
          - --pretty
          - --show-error-codes
          - --show-error-context
          - --ignore-missing-imports
        additional_dependencies:
          - types-requests
          - types-setuptools
          - types-PyYAML
