APP_NAME = "jira-select"


ENTRYPOINT_PREFIX = "jira_select"

COMMAND_ENTRYPOINT = f"{ENTRYPOINT_PREFIX}.commands"
SOURCE_ENTRYPOINT = f"{ENTRYPOINT_PREFIX}.sources"
FORMATTER_ENTRYPOINT = f"{ENTRYPOINT_PREFIX}.formatters"
FUNCTION_ENTRYPOINT = f"{ENTRYPOINT_PREFIX}.functions"
